### ISSUE TITLE
feat: JSON emit_null option

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/active-model#14]
At the moment we're unable to emit null JSON (as this is the crystal default when an option is not supplied).

> emit_null: if true, emits a null value for nilable properties (by default nulls are not emitted)
https://crystal-lang.org/api/0.30.1/JSON.html

We ought to be able to add an additional option which will then be forwarded to the options given to the [JSON mapping for each property](https://github.com/spider-gazelle/active-model/blob/master/src/active-model/model.cr#L302). I can't see a nice enough way to add this without an additional opt on the attribute definition, although this is where I'd expect it to be anyway.

Happy to submit a PR if you're okay with the design of this;

```crystal
attribute description : String, emit_null: true
```

```crystal
JSON.mapping(
  {% for name, opts in PERSIST %}
    {% if opts[:converter] %}
      {{name}}: { type: {{opts[:klass]}} | Nil, converter: {{opts[:converter]}}, emit_null: {{opts[:emit_null]}} },
    {% else %}
      {{name}}: { type: {{opts[:klass]}} | Nil, emit_null: {{opts[:emit_null]}} }
    {% end %}
  {% end %}
)

macro attribute(name, converter = nil, mass_assignment = true, persistence = true, emit_null = false, **tags, &block)
  # ...
end
```

**Comment by stakach** [comment]
totally missed this, yeah feel free to make a pull request
