### ISSUE TITLE
Attributes should not be nillable by default

### ISSUE THREAD

**Issue by caspiano** [spider-gazelle/active-model#18]
The current behaviour is that all attributes are nillable.
This is quite cumbersome as every attribute access requires a `nil` check.

Changing to stricter serialization would do away with the need for `presence` checks on fields, and for failures a custom error could be thrown to indicate the missing fields.

**Comment by stakach** [comment]
[Bindata](https://github.com/spider-gazelle/bindata/blob/master/src/bindata.cr#L385) achieves this by assigning the defaults to the attribute definitions.

Works pretty well
