### ISSUE TITLE
refactor: JSON.mapping -> JSON::Serializable

### ISSUE THREAD

**Issue by caspiano** [spider-gazelle/active-model#19]
Currently, `active-model` generates a `JSON.mapping` off the specified attributes.
Moving to an annotation flow would improve interop with other libraries and frameworks.

This change would be a good part of the progress towards solving spider-gazelle/rethinkdb-orm#2

**Comment by dukenguyenxyz** [comment]
The PR to resolve this issue (https://github.com/spider-gazelle/active-model/pull/26) is currently blocked by the following issue which I already made a PR (https://github.com/crystal-lang/crystal/issues/10265)
