### ISSUE TITLE
Custom setters difficult with macro finished usage

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/active-model#3]
Typical preface that I'm no expert at macros so you may have a way better way of handling this situation than I do. I have a bit of an odd situation where clients outside my control pass me a JSON string as a query param. This can come in as a GET request to
```
http://localhost:3000/lrs/agents?agent=%7B%22mbox%22%3%20%22mailto%3Atest%40example.org%22%7D&another_param=foobar
```
And if I call a `params.to_unsafe_h` (from Amber params) I get the following hash:
```crystal
{ "agent" => "{\"mbox\": \"mailto:test@example.org\"}", "another_param" => "foobar"}
```
Which becomes difficult so properly serialize in a nested way as I'd want to serialze the agent parameter into an agent and the other parameters as per their defined type. In this instance the `agent` key is the only key that will ever be serialized as JSON, annoyingly. Keeping the type as a string and chaining/externalising the serialization of `agent` is straightforward enough:
```crystal
class Serializer < ActiveModel::Model
  attribute agent : String
  attribute another_param : String
end

class Agent < ActiveModel::Model
  attribute mbox : String
end

def show
  serialized_params = Serializer.new(params.to_unsafe_h)
  agent = Agent.new(serialized_params.agent)
end
```
But I was kind of hoping to be able to do something like:
```crystal
class Serializer < ActiveModel::Model
  class Agent < ActiveModel::Model
    attribute mbox : String
  end

  attribute agent : Agent
  attribute another_param : String

  def agent=(value : String)
    self.agent = Agent.from_json(value)
  end
end

def show
  Serializer.new(params.to_unsafe_h).agent
end
```
-----

Now I have got this working with the following code:
```crystal
macro finished
  def initialize(params : HTTP::Params | Hash(String, String) | Tuple(String, String))
    previous_def(params)
    self.agent = params["agent"]?
  end

  def agent=(value : String | Nil)
    if value.is_a? String && !value.empty?
      self.agent = Agent.from_json(value)
    end
  end
end
```
But it feels marginally more difficult than if the finished macro wasn't being used (or so I believe). I was hoping I'd have been able to overload the setter for `value : String` for all initialize types, but AFAICT the finished macro literally runs last, taking precedence of any function definitions I make within the class itself. Is that accurate? If so, can you see any ways that this could be improved?

**Comment by stakach** [comment]
Sweet man, thanks for pointing that out.
I think `attribute agent : Agent` is something we will support and we'll call from_json on it or Agent.new if it's an ActiveModel etc.

I assume you want to use the validations too? Otherwise you are possibly better off using the built in [Crystal lang JSON mapping](https://crystal-lang.org/api/0.27.2/JSON.html#mapping%28_properties_%2Cstrict%3Dfalse%29-macro)

Example usage in one of our projects
https://github.com/acaprojects/meraki-scanner/blob/master/src/models/event.cr

At least until we add that support in.

**Comment by stakach** [comment]
There is also a `__customize_orm__` macro that you can define that runs as part of `finished`

**Comment by jackturnbull** [comment]
Ah, I do need the validations in this instance as I'm primarily going to be using this for validating JSON parameters into my app to begin with rather than going for the full ActiveRecord ORM pattern on it - although that's another reason I've decided to have a play with it as I like the flexibility

Thanks for the feedback on this one but I think I'm having a little bit of writers block and I can't corrall it into doing what I need using the `__customize_orm__` macro (although I can see that it ought to be doing most of what I need, I'll return to this again I'm sure.)
